build: false

install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy scipy
  - pip install scikit-learn
  - pip install matplotlib
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov

test_script:
  - python tests.py
